### PR TITLE
Fully support Zabbix 6.0+ Server High Availability

### LINKED ISSUE #42: upgrade issue
**Describe the bug**
unable to upgrade from 6.0.13 to 6.4. I can't seem to find a way to comment out HANodeName so that the server can start up in standalone mode.

**Version of Helm and Kubernetes**: 1.27

Any suggestions?

### LINKED ISSUE #98: [zabbix-community/zabbix] unstable connection to the zabbix-server service when in HA mode
random (i.e., sometimes connection succeeds, sometimes fails) connection timeout to the port 10051 on the `zabbix-server` service.

**Version of Helm and Kubernetes**:

kubernetes version: v1.22.8

helm version: using ArgoCD 2.10 for zabbix deployment, so helm is v3. if the exact helm version is relevant for this issue, I will dig deeper.

**What happened**:

zabbix agents are unable to connect to the server for heartbeat message or active check most of the time:
```
2024/06/20 13:29:20.039885 [101] active check configuration update from host [zabbix-agent-host] started to fail
2024/06/20 13:30:13.989139 [101] cannot connect to [zabbix.company.name:10051]: dial tcp :0->13.13.13.13:10051: i/o timeout
2024/06/20 13:30:13.989185 [101] sending of heartbeat message for [zabbix-agent-host] started to fail
```
coincidentally, `telnet zabbix-zabbix-server.monitoring 10051` randomly succeeds or fails, so the problem is not in the ingress.

**What you expected to happen**:

connection should happen every time.

**How to reproduce it**:

I think, this could reliably be reproduced on any HA installation. below I will post the relevant `values.yaml` entries (because it might as well be misconfiguration on my part), feel free to request any additional details.

**Anything else we need to know**:

if I try to connect to individual zabbix-server pods via port 10051, only 1 (of 3) could be connected to (and it connects reliably). probably, the service is unaware, which pod is active at the moment and tries to connect randomly or something like that.

relevant values:

```yaml
zabbixServer:
  extraEnv:
    - name: ZBX_AUTOHANODENAME
      value: "fqdn"
  haNodesAutoClean:
    image:
      repository: timescale/timescaledb
      tag: latest-pg16
  replicaCount: 3
  service:
    type: ClusterIP
```

the other (relevant) values are unchanged.

when in not-HA mode, it works 100% of the time.

### PR DESCRIPTION
**Pull request by fibbs**
This PR (finally) implements full Zabbix Server High Availability in Kubernetes and fixes some design problems of this Helm Chart done before (by me).

The following problems are being addressed:
- fixes #42 
- fixes #98 

#### Zabbix HA mode switchable on and off / Major Release upgrades
Challenges that were to overcome:
- Zabbix Server doesn't allow to upgrade or to initialize database  schema when running in HA mode (HA mode enabled meaning the zabbix  server pod has the "ZBX_HANODENAME" env variable set
- database schema upgrade in case of a major release upgrade of Zabbix  Server is being issued by the zabbix server process, there is no  one-shot program to do this

The approach being used is the one described here: https://github.com/zabbix-community/helm-zabbix/issues/42#issuecomment-2471521576

- added a portion in values.yaml generally switching "Zabbix Server HA" on or off. If turned off, the Zabbix Server deployment will always be started with 1 replica and without the ZBX_HANODENAME env variable. This is an easy-to-use setup with no additional job pods, but it's not possible to just scale up zabbix server pods from here
- when .Values.zabbixServer.zabbixServerHA.enabled is set to true, a Kubernetes Job, marked as Helm post-install,post-upgrade hook, is being deployed together with a Role, Rolebinding and ServiceAccount, allowing this job pod to execute some changes via Kubernetes API. The job runs after each installation and upgrade process, scales down zabbix server pods if needed, manages db entries for active HA and non-HA server nodes being connected to the database, etc. Additionally, this job figures out whether a migration from a non-HA enabled setup to a HA-enabled one has been done, and handles necessary actions (scale down pods, delete entries in database) accordingly
- the sidecar containers running together with the Zabbix Server pods have been updated not only to prevent starting Zabbix Server pods when database is not available, but also when the schema version of the database is not yet the correct one, adding an additional layer of preventing pods from crashing

Tests have been done, and are still being done with Zabbix versions 6.0, 6.4 and 7.0 (6.2 being out of support):
- plain installation, with HA enabled and HA disabled
- upgrade from one to the other version, including skipping 6.4 and
  going from 6.0 directly to 7.0
- migrating from HA-enabled to non-HA enabled and vice versa
- upgrading while switching vom non-HA to HA enabled setup

#### Sidecar approach to mark "active" server node
The active node starts all its processes, like pollers, timer, alerter, escalators, etc. while the standby nodes only have the main zabbix_server process (the one that reads the config file) plus a "ha manager" running.

I have used a sidecar container on each of the zabbix_server pods, periodically gathering the amount of zabbix_server processes and comparing them against a threshold (5) to find out whether the local node is "active" or "standby". Depending on this information, we update a label on the pod.

When HA mode is enabled, the Zabbix Server service manifest gets an additional selector, which is the label set by the sidecar mentioned above. This way, the service can always be used to contact the one and only "active" Zabbix Server node

The reason to implement it this way and not by probing the port number, which was my initial approach, is that probing the port of Zabbix Server will make it generate a message in the log, stating that a connection without a proper payload has been initiated towards the Zabbix Server.

#### Special notes for your reviewer:

Currently, I have the two images needed for a) the database create/upgrade job and b) the sidecar checking HA status and setting the labels being built in my company's (non-private) Gitlab instance and I have hosted the images on my company's registry. I would like to migrate my code into this repository, and set up Github automations to make Github build and host the images. @aeciopires can you help me setting this up? What would be a good place to put the code within this repo? Should we just add a subdirectory "images" under /charts/zabbix? Please let me know...

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/zabbix-community/helm-zabbix/blob/master/CONTRIBUTING.md) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

For the not fulfilled checkboxes additional commits will follow.

### CODE REVIEW

**Review by aeciopires — APPROVED** [review]
Hi @fibbs!

Thanks for your great contribution. 
I knew it would be great to wait for a solution from you.

Regarding hosting the image code, I think it's worth you creating another repository on GitHub and I can help you build the pipeline code using github actions.

You can create a repository using your personal account or you can create another one under the zabbix-community organization.

We'll leave this repo only for the helm-chart theme. What do you think?

**Comment by fibbs** [comment]
> Regarding hosting the image code, I think it's worth you creating another repository on GitHub and I can help you build the pipeline code using github actions.
> 
> You can create a repository using your personal account or you can create another one under the zabbix-community organization.
> 
> We'll leave this repo only for the helm-chart theme. What do you think?

I am fine with having another repo within this organization "zabbix-community". Will it work with Github pipelines to have one repository for two Dockerfiles + stuff? One of them needs a "matrix build", so from one (sub?)repository several images will have to be built. In Gitlab, I have defined a list of versions (tags of upstream zabbix-server-pgsql images) which will be used to build one image for each, as the image bases off the zabbix server image.

**Comment by fibbs** [comment]
Request was not meant to merge yet :-) I am yet missing doc comments for values.yaml + version bump

**Comment by fibbs** [comment]
I would open an additional PR for docs + version bump, though.
@aeciopires Do you think this is worth a major version 6.0.0? Actually, there have been quite some changes, but I believe there are not "blocking" issues. Nevertheless, I would like to add a portion of documentation on how this all works.

**Comment by fibbs** [comment]
> > Regarding hosting the image code, I think it's worth you creating another repository on GitHub and I can help you build the pipeline code using github actions.
> > You can create a repository using your personal account or you can create another one under the zabbix-community organization.
> > We'll leave this repo only for the helm-chart theme. What do you think?
> 
> I am fine with having another repo within this organization "zabbix-community". Will it work with Github pipelines to have one repository for two Dockerfiles + stuff? One of them needs a "matrix build", so from one (sub?)repository several images will have to be built. In Gitlab, I have defined a list of versions (tags of upstream zabbix-server-pgsql images) which will be used to build one image for each, as the image bases off the zabbix server image.

I have created a new repository https://github.com/zabbix-community/helm-zabbix-ha-helper-images with two sub-directories, each being migrated from one git repository in my local Gitlab system, thus, every of the subdirectories contain a .gitlab-ci.yml. I have left those there so you can see how the images where built in my local system, and (hopefully) transform this to Github's "language". 

If anything unclear, just get back to me :-)

**Pull request merged**
