### PR TITLE
Update statefulset-postgresql.yaml

### PR DESCRIPTION
**Pull request by alezkv**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by aeciopires** [comment]
Hi @alezkv!

I'm closing this Pull Request because I included your changes in this PR: https://github.com/zabbix-community/helm-zabbix/pull/25 

Thanks for your contributition.

**Comment by alezkv** [comment]
@aeciopires Great way how to not grow projects contributes. Just saying.

**Comment by aeciopires** [comment]
Hi @alezkv,

Sorry if I gave the wrong impression. My PR has been waiting since January/2023 and it contains a big change. I have included your changes in my PR with the intention of speeding up solutions and have included your name in the release notes as a thank you for your work. I have not removed your credits.

Imagine the time and work you would have if you had to understand my merge, resolve code conflicts and only then be able to be reviewed again...

You have the right to be ungry/sad, but I did not intend to harm your contribution or the evolution of the project.

You are welcome to open new Pull Requests and issues.

Have a nice week

See this message https://github.com/zabbix-community/helm-zabbix/releases/tag/zabbix-4.0.0

**Comment by alezkv** [comment]
@aeciopires Thanks Aécio for explanation. I personally have no expectation or strong feeling about that. And cleanly understand the intent for that action.

Thanks again for your time and effort.

**Pull request closed without merging**
