### PR TITLE
feat(zabbix): add externalTrafficPolicy to zabbixserver service

### PR DESCRIPTION
**Pull request by tomsozolins**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md

### CODE REVIEW

**Comment by sa-ChristianAnton** [comment]
Hi!

Thanks for your contribution! Could you please upgrade the version of the chart to 3.3.2 in Chart.yaml and add the new value you have introduced into the values.yaml? Afterwards, please regenerate the documenation as described [here](https://github.com/zabbix-community/helm-zabbix/blob/master/CONTRIBUTING.md).

Thanks

**Comment by aeciopires** [comment]
Hello @tomsozolins and @sa-ChristianAnton!

I have this Pull Request opened  https://github.com/zabbix-community/helm-zabbix/pull/10. If it merged before, will need change the version chart again and will need to solved possible conflicts.

**Comment by sa-ChristianAnton** [comment]
...and exactly that happened now. Please update version to 3.4.1.

**Comment by tomsozolins** [comment]
@aeciopires Hello! I'm quite busy currently to make the changes.
Feel free to merge these changes into your existing pull requests if you are about to release or i will do it later when have time.

**Comment by sa-ChristianAnton** [comment]
Pulled changes made by tomsozolins in PR #11 into this PR (adding quote statements to annotations) and updated version and documentation.
@aeciopires could you please review?

**Review by sa-ChristianAnton — APPROVED** [review]

**Review by aeciopires — APPROVED** [review]
Hi @tomsozolins and @sa-ChristianAnton!

Thank you for your contribution.

This Pull Request is very good.

**Pull request merged**
